### ISSUE TITLE
Practica 10

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-proyecto-contrato-inteligente-equipo-aras#1]
[Practica 11 Redacción de Contrato.pdf](https://github.com/user-attachments/files/18091223/Practica.11.Redaccion.de.Contrato.pdf)

**Comment by Luz1727** [comment]
calificacion 50%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
